/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "vibrant-green": "#2DD60E",
              "deep-black": "#0B0B0F",
              "soft-grey": "#F2F2F2",
              "mint": { "400": "#4ade80", "500": "#22c55e", "600": "#16a34a" },
              "inverse-surface": "#e5e2e3",
              "secondary-container": "#16a34a",
              "on-primary-fixed": "#320046",
              "surface-variant": "#353436",
              "on-secondary-fixed-variant": "#004e5a",
              "on-surface": "#e5e2e3",
              "secondary": "#4ade80",
              "tertiary-fixed": "#e2e2e2",
              "on-tertiary-container": "#ffffff",
              "tertiary": "#c6c6c7",
              "error": "#ffb4ab",
              "on-primary-fixed-variant": "#75009e",
              "on-error-container": "#ffdad6",
              "primary-container": "#22c55e",
              "on-primary-container": "#ffffff",
              "background": "#131314",
              "surface-container-lowest": "#0e0e0f",
              "on-primary": "#520070",
              "primary-fixed": "#f9d8ff",
              "surface-bright": "#3a393a",
              "outline-variant": "#514254",
              "surface-container-highest": "#353436",
              "on-secondary-container": "#00515d",
              "tertiary-container": "#757777",
              "on-secondary": "#00363e",
              "primary-fixed-dim": "#ecb1ff",
              "secondary-fixed": "#a2eeff",
              "tertiary-fixed-dim": "#c6c6c7",
              "on-tertiary-fixed-variant": "#454747",
              "surface-container": "#201f20",
              "inverse-primary": "#9900ce",
              "outline": "#9d8ba0",
              "error-container": "#93000a",
              "secondary-fixed-dim": "#2fd9f4",
              "on-tertiary-fixed": "#1a1c1c",
              "surface-tint": "#ecb1ff",
              "on-background": "#e5e2e3",
              "primary": "#4ade80",
              "on-tertiary": "#2f3131",
              "surface-container-high": "#2a2a2b",
              "on-error": "#690005",
              "surface": "#131314",
              "surface-dim": "#131314",
              "on-secondary-fixed": "#001f25",
              "surface-container-low": "#1c1b1c",
              "inverse-on-surface": "#313031",
              "on-surface-variant": "#d5c0d7"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "container-max": "1440px",
              "unit": "8px",
              "margin-mobile": "20px",
              "margin-desktop": "64px",
              "gutter": "24px"
      },
      "fontFamily": {
              "sans": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
